#!/usr/bin/env bash

# based on https://codeberg.org/arran/dotfiles/src/branch/master/private_dot_local/scripts/executable_cwd-term

# Open a new terminal in the current working directory of a focused terminal
terminal="kitty"

# Get the process id of the currently selected window
pid=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.type=="con") | select(.focused==true).pid')
# Get the name of this process
pname=$(ps -p ${pid} -o comm= | sed 's/-$//')

# If the process name matches the $terminal, obtain the CWD and echo the result.
if [[ $pname == $terminal ]]
then
    # Get parent process id
    ppid=$(pgrep --newest --parent $pid )
     
    # Get the current working directory
    workdir=$(readlink /proc/${ppid}/cwd)
    swaymsg exec "${terminal} --single-instance --directory ${workdir}" # && notify-send -t 2000 "Terminal in $workdir"
else
    notify-send -t 2000 -- "Failed to obtain current directory from $pname"
fi
