-----BEGIN PGP MESSAGE-----

hQIMA48YbIE+baudAQ/+J4xEdaUY/olTXS90I3KXuiX08ubwJ5o18duM8WE1r7Rp
i1xAInd2KMQLEdSysoUpW5SLkICHRWaJuGAkrIk1C9hZ/kMHeF8v6LKWny2ep/M2
ptRlG4iIekoajWVxiN+PZtJu4Tx0vi03SrOb29t7R0ekbzjJJMr5E9Gpvm0fjnEb
Q3R3nrW+CRqgLwSl4vV+/MrY+IB+BrzOtAcCdAW+V+dFNxvH2x6PHPP8yYpNmzCY
DAKGKSsHMVwBV0+O5a1bSXQ06hltD0eUvoHKoqlYylxALHLqSKumJoQ/NVEJH9uM
fL0tkQHlmgmMqtcqYQ/ZjQUC7htA3B6sPybc1kFMD5PaVcmsrtWKJ2HBaS2hKjKa
BV9u9UuNln+kUEu2Hf11bk1CGUB4rfIgZceLk/mfWWPv7nSuTqk4oaHkt2lEascL
VqPGCD4UZYVlOJC9dK6G+k1/GCpAwpk20UGFR1uYeb/hp4996dj6AiYLbnPMMbph
1UmjoBr4YTDz0GxLkwJLXDJoHhR6PaqQ2UzDbAjJsX+/uN/bmzmyzdiN3GKNxTff
fEXk7H/ZcPniXHHD1iEHMaXMVn1pVLZ1K8CvQMfq6Pl+1/SO5BuScsAs3woUidc9
LGivPW3tvOUo77vnsBF7skwYVgFB02D6ZF25N88r/dJYbFRKApdhMQ2wjTZtmEzS
6QEYAtY7CTOQlzHrdKSauJSAgZYrQPtTTiIQYEI5a6ro5YvIMf+9Mxtxw/lka5Ml
GH9kv19YEG+LJ47WXFa7HaPHOsIe7oCNffzrCNeO8yTGaLBgn2QK/1F50rUdCGSY
T0Xul0dc2PbMIQrPSKGOG6u2t8x+eKJWiHHePE8Wti2pLldKVi2uNRfDyC2MQgoT
mQ9o0PpP0loHePDht/6YMXYDRIIm630IauXY2mr63C+Ws5zXCISV3hgBuBBm151T
Bx/3HO4w8IKhw6AuUxV/FDso3ENrV/x1SmnLfzta0/z4M/5VDeU82wO0YQHAOOg5
sw8jGUo+Nl2Z3S8QDt93EpjMfgdsWK0nNCePH4GIfEVf/t9kfEpFHLpeKt+BBJ0N
LL0PEW1ENGNOIhdfHST6JXD77MdxDNAf3tv4lIbRPj25XsJXmrrfp3h0GCo+WRFe
9qhH5bu2UORCoNuwolPyB6qA57qzkfUh5xoyhLBiG0GmC8n/fOXjC+f4dP6G7DG7
TjRK+ACnFSmc13uSbhKt0K7oHvIFFuns/KgHmn49lk4pB3i6hO/wOnLxTR+YtZ5T
L9VVW+vRnh17mgQ5nZU6WzKkg33m85bPYZhOsRQpo1qD72F8Qglm4PCcT5Bn+KJb
d8ZEXyigXmmWdXnrPcqca03pCHEvQos/+49rpUjsadvJjqO2BKx/nQZBKgZ0QHb2
OVtP8+SbidqtNtMfLgwWazz02un9zLEkG4rloadJZJgpUIbN62WWqN8qLzgos2r3
Nw1KPRDmQtNAGV8BLEl75YPzYUDTZxEQ5wTCgIjSE73Qy/5/itpSRbTt27hWNFI6
8gDcSl0pKwM8ZxRFrP8n+0OUt6qeIX4DUWWJpjCdDuQ=
=kPzc
-----END PGP MESSAGE-----
